### ISSUE TITLE
Add Difficulty column to Questions

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/Core#19]
Please add the **difficulty column** **(string)** to the **questions** model. Please also update the corresponding **serializers** so that difficulty can be accessed via its corresponding endpoints.

On the model, use the **following syntax** to ensure the difficulty can be of the following options: **Easy, Medium, and Hard.**

```
format = models.CharField(
        choices=(
            ("t", "text"),
            ("h", "html"),
            ("m", "mathjax"),
        ),
        max_length=1,
    )
```

<img width="162" alt="Screenshot 2021-04-29 at 1 12 53 PM" src="https://user-images.githubusercontent.com/43223682/116591321-ac378500-a8ec-11eb-8946-f268d24b8b7c.png">

**Comment by pmkuny** [comment]
Hi @MathyouMB - can myself or @aidutcher take this? We are peer programming together. I would submit the PR with credit to him.

**Comment by MathyouMB** [comment]
> Hi @MathyouMB - can myself or @aidutcher take this? We are peer programming together. I would submit the PR with credit to him.

Hey :)  

Yeah for sure! I'll assign you to this.
