### ISSUE TITLE
Attempts Submission Column + email, question validation

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/Core#21]
Please add the **Attempts** column **(int)** to the **Submission model**.

Please also add validation to the model that ensures two submissions cannot be created with the same **email and question id**. 

Add a test that validates that the model **ensures two submissions cannot be created with the same email and question id**.

<img width="120" alt="Screenshot 2021-04-29 at 1 22 17 PM" src="https://user-images.githubusercontent.com/43223682/116592402-f53c0900-a8ed-11eb-8d12-2c68725dda12.png">

**Comment by MathyouMB** [comment]
@ApprenticeofEnder  we can pair program on this when you are free to start :)

**Comment by ApprenticeofEnder** [comment]
I'm green! 

Got a few ideas already.

**Comment by ApprenticeofEnder** [comment]
Done and dusted! #35
